apiVersion: v1
kind: Service
metadata:
  name: incasur-psql-service
  namespace: "2023241041"
spec:
  selector:
    app: incasur-db
  ports:
    - protocol: TCP
      port: 5432      # Puerto que usa el servicio
      targetPort: 5432 # Puerto que expone tu Pod (Timescale/Postgres por defecto)
